utc: "2023-08-26 16:00:00 -0500" #Required. The start time of the event. Best to use UTC format, but may work in other date formats too.
name: "Melanie and Jamie" #Required. The human-readable name of the event
logo: BA4E8AD2-2390-4356-BCB2-7F710F2068AA.jpeg #Required. logo for the event. replace this logo in the project or add a new file and change the value of this variable
description: "Melanie and Jamie are getting married in Brooklyn!"
externalLink: "http://melanieandjamie.github.io" #Required. link to the main event page. this could be a webpage, a facebook event, an eventbrite page, where ever the main webpage is for your event
url: #(Optional) the full URL for this countdown page. This is neccesary for facebook share previews
facebookEventLink: #(Optional) if you have a facebook event, put the link here and we'll add a "RSVP on facebook" link at the bottom.
hashtag: "" #(Optional) hashtag for the event, example "#hashtag". must be in quotes.
colors: #(Optional)
  background: "#000000" #color of the background of the page
  primary: "#F28500" #primary color for the page
  secondary: "#FFE5B4" #secondary color for the page
  textcolor: "#FE2C54" #color of the text, which is overlayed on the primary color
fontfamily: "'Arial', sans-serif" #optional
